### ISSUE TITLE
FS_SEL Configuration

### ISSUE THREAD

**Issue by lolzballs** [japaric/mpu9250#8]
There should be a method of changing the full scale of the measurements, specified via the FS_SEL bits of the various configuration registers.

I'm not very familiar with API design in Rust, so I'm looking for guidance in implementing this. Would it be best to have enums representing the different scale modes that could be present?

**Comment by japaric** [comment]
> Would it be best to have enums representing the different scale modes that could be present?

Yeah, I would implement this using an enum like it's done in the [`a_filter`](https://github.com/japaric/mpu9250/blob/4cd19cc74d71de6f3edf532d53537ab67c70d514/src/lib.rs#L240) method.
